version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '1m'
    max-file: '1'
  driver: json-file

services:
  app:
    logging: *default-logging
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: hd-app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://hd-redis:6379
    tty: true
    command: ["bash"]

  redis:
    image: redis:6-alpine
    container_name: hd-redis
    logging: *default-logging
